### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by Mostafa-ewida** [Hack-Maze/front-end#101]
![Image](https://github.com/Hack-Maze/front-end/assets/71707534/0d42f8df-c6cf-4f45-a709-261ac56977f9)

**Comment by mahmoud-abo-al-ela** [comment]
ده اي ده

**Comment by mahmoud-abo-al-ela** [comment]
backend should handle it. @Mostafa-ewida

**Comment by juba0x00** [comment]
> ده اي ده



![Image](https://github.com/Hack-Maze/front-end/assets/73611543/8cffa658-11d5-4eeb-817f-cf8a77c1d8ce)

**Comment by Mostafa-ewida** [comment]
you can do  a basic  error handling with `something went wrong` nothing more

**Comment by mahmoud-abo-al-ela** [comment]
يعني الباك ميعرفش يرجعهالي من عنده رسالة ايرور طبيعيه إن الصورة مساحتها كبيره @Mostafa-ewida

**Comment by mahmoud-abo-al-ela** [comment]
لاني لو عملتها زي مانت بتقول ممكن يظهر ايرور من حاجه تانيه واليوزر م هيفهم سبب الايرور

**Comment by Mostafa-ewida** [comment]
> لاني لو عملتها زي مانت بتقول ممكن يظهر ايرور من حاجه تانيه واليوزر م هيفهم سبب الايرور

انا فاهم والله يا محمود , بس زياد مش فاضي اوي وفي حاجات اهم تتعمل , ال issue  كدا كدا low
