### ISSUE TITLE
add max width for maze title and subtitle

### ISSUE THREAD

**Issue by juba0x00** [Hack-Maze/front-end#104]
@mahmoud-abo-al-ela 

![Image](https://github.com/Hack-Maze/front-end/assets/73611543/182cc051-43af-40cd-a456-10c3c3f20e21)

**Comment by mahmoud-abo-al-ela** [comment]
هخلي اما يجي يكريت يبقي عدد الحروف أقل من ٣٠ مثلا للtitle و ٥٠ للصب م هسيبها مفتوحه

**Comment by Mostafa-ewida** [comment]
> هخلي اما يجي يكريت يبقي عدد الحروف أقل من ٣٠ مثلا للtitle و ٥٠ للصب م هسيبها مفتوحه

دا في السطر , ماشي انما متحطش limit  في ال front  في مimits  في ال back   الفكره خليه ي limit  ال سطر او ال representation  بس 
@mahmoud-abo-al-ela
