### ISSUE TITLE
created-mazes and solved-mazes

### ISSUE THREAD

**Issue by juba0x00** [Hack-Maze/front-end#114]
@mahmoud-abo-al-ela 

- [ ]  fix created-mazes

the created mazes you use are getting the current user-created mazes, even if you are viewing other user profile

use `/api/v1/profile/created-mazes/{profileId}` to get another user created mazes

- [ ] use solved-mazes endpoint 
`/api/v1/maze/solved-mazes`: get the solved-mazes of the current user
`/api/v1/maze/solved-mazes/{profileId}`: get the solved-mazes using the profileId

![Image](https://github.com/Hack-Maze/front-end/assets/73611543/c1236812-5743-40e9-bf49-7f36e212a02b)

**Comment by mahmoud-abo-al-ela** [comment]
اي المشكله ؟؟ @juba0x00
