### ISSUE TITLE
maze list

### ISSUE THREAD

**Issue by Mostafa-ewida** [Hack-Maze/front-end#117]
- [ ]  fix borders for all mazes not floating 

![Image](https://github.com/Hack-Maze/front-end/assets/71707534/84f909f2-266a-4013-b466-4e10f0d6b78c)

- [ ] please add Explore mazes button again if there is maze list  forward it to the learn page

**Comment by mahmoud-abo-al-ela** [comment]
يعم افتحه شاشه كامله الموقع م ريبونسف + explore موجوده لما تكون كل الميز complete 
@Mostafa-ewida
