### ISSUE TITLE
use streak and points

### ISSUE THREAD

**Issue by Mostafa-ewida** [Hack-Maze/front-end#123]
![Image](https://github.com/Hack-Maze/front-end/assets/71707534/8fad7d19-a1cc-41fb-8de9-e8c65684dc45)

to be implemented  by marym

**Comment by mahmoud-abo-al-ela** [comment]
ضيفهم ف current endpoint

**Comment by Mostafa-ewida** [comment]
> ضيفهم ف current endpoint

استخدمهم بقا بال icons  دي @mahmoud-abo-al-ela
