### ISSUE TITLE
Can't open maze

### ISSUE THREAD

**Issue by juba0x00** [Hack-Maze/front-end#78]
- [ ] remove unnecessary requests `(/api/v1/maze` request when opening any maze)
- [x] fix open maze issue: the backend returns the maze preview, but the front shows 404

@mahmoud-abo-al-ela

**Comment by mahmoud-abo-al-ela** [comment]
اي تاني يا وديع

**Comment by mahmoud-abo-al-ela** [comment]
ايوه كده دلعني
