### ISSUE TITLE
reactivate roadmap pages

### ISSUE THREAD

**Issue by Mostafa-ewida** [Hack-Maze/front-end#89]
please make the roadmap pages visible through a drop down list in learn or something , it is Urgent for the Doctor , she might ask for it 
@mahmoud-abo-al-ela

**Comment by juba0x00** [comment]
@mahmoud-abo-al-ela 

URGENT, idiot

**Comment by mahmoud-abo-al-ela** [comment]
هو اي الurgent ف كده يعني هو اي حاجه عاوز تحطها ف الموقع وخلاص متفتحها يعم من اي داهيه تانيه 
@juba0x00
